"""add search_configs table

Revision ID: 2333044e6a3b
Revises: 3e83431654c5
Create Date: 2026-05-30 21:30:52.184564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2333044e6a3b'
down_revision: Union[str, Sequence[str], None] = '3e83431654c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_configs')
    # ### end Alembic commands ###
